const products = [
  {
    _id: '1',
    name: 'Queen Panel Bed',
    image: '/images/product-1.jpeg',
    description:
      'Full size Queen Bed for long time use ',
    brand: 'ComfyHouse',
    category: 'Furniture',
    price: 12389.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '2',
    name: 'King Panel Bed',
    image: '/images/product-2.jpeg',
    description:
      'Introducing the King Panel Bed . Most Selling item .',
    brand: 'ComfyHouse',
    category: 'Furniture',
    price: 14599.99,
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: '3',
    name: 'Single Panel Bed',
    image:  '/images/product-3.jpeg',
    description:
      'IN low budget and quality is awesome.',
    brand: 'ComfyHouse',
    category: 'Furniture',
    price: 13399.99,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: '4',
    name: 'Twin Panel Bed',
    image:  '/images/product-4.jpeg',
    description:
      'Best deal for couples strong and long lasting ',
    brand: 'ComfyHouse',
    category: 'Furniture',
    price: 14699.99,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: '5',
    name: 'Fridge',
    image: '/images/product-5.jpeg',
    description:
      'Best Electronic item for your Home ',
    brand: 'Samsung',
    category: 'Electronics',
    price: 14559.99,
    countInStock: 7,
    rating: 4.5,
    numReviews: 10,
  },
  {
    _id: '6',
    name: 'Dresser',
    image:  '/images/product-6.jpeg',
    description:
      'Soft and High Quality Material ',
    brand: 'ComfyHouse',
    category: 'Furniture',
    price: 2439.99,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '7',
    name: 'Couch',
    image:  '/images/product-7.jpeg',
    description:
      'Soft and High Quality Material ',
    brand: 'ComfyHouse',
    category: 'Furniture',
    price: 12000.99,
    countInStock: 0,
    rating: 3.8,
    numReviews: 12,
  },
  {
    _id: '8',
    name: 'Table',
    image:  '/images/product-8.jpeg',
    description:
      'Smooth Finish and High Quality Material ',
    brand: 'ComfyHouse',
    category: 'Furniture',
    price: 2999.99,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
]

export default products
